const { ChunkExtractor } = require('@loadable/server');
const { statsPath } = require('./constants');
const stats = require(statsPath) || {};

const extractor = new ChunkExtractor({
  // Read the stats file generated by webpack loadable plugin.
  // The file will not exist in develop stages.
  stats,
  entrypoints: [],
});

// extractor.collectChunks() will wrap the application in a ChunkExtractorManager
const wrapRootElement = ({ element }) => extractor.collectChunks(element);

const onRenderBody = ({ setPostBodyComponents, setHeadComponents }) => {
  // Set link rel="preload" tags in the head to start the request asap. This will NOT parse the assets fetched
  setHeadComponents(extractor.getLinkElements());

  // Set script and style tags at the end of the document to parse the assets.
  setPostBodyComponents([
    ...extractor.getScriptElements(),
    ...extractor.getStyleElements(),
  ]);

  // Reset collected chunks after each page is rendered
  extractor.chunks = [];
};

module.exports = {
  wrapRootElement,
  onRenderBody,
};
