name: Gatsby Publish

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Orainsink/gatsby-gh-pages-action@v1.1
        with:
          who-to-greet: 'Orainsink'
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_HEWEATHER_KEY: ${{ secrets.GATSBY_HEWEATHER_KEY }}
          GATSBY_SENTRY_AUTH: ${{ secrets.GATSBY_SENTRY_AUTH }}
          GATSBY_SENTRY_DSN: ${{ secrets.GATSBY_SENTRY_DSN }}
          TRACKING_ID: ${{ secrets.TRACKING_ID }}